site_name: C a a t a l y s t
site_url: https://caatalyst.atlassian.net/
site_author: Harshav

theme:
  name: material
  favicon: assets/dna.png
  logo: assets/cube.png
  features:
    - navigation.tabs
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode